- name: '未着手 (Open)'
  description: 'イシューが作成されたばかりで、まだ誰も作業を開始していない状態。'
  color: 'ededed'
- name: '作業中 (In Progress)'
  description: '誰かがイシューに取り組み始めた状態。'
  color: '207de5'
- name: 'レビュー待ち (Review)'
  description: '作業が完了し、レビューを待っている状態。'
  color: 'ffc107'
- name: '完了 (Closed)'
  description: 'イシューが解決済みで、完了した状態。'
  color: '28a745'
- name: '保留 (On Hold)'
  description: '一時的に作業を中断している状態。'
  color: '6c757d'
