steps:
    - name: 'gcr.io/cloud-builders/docker'
      # Secret Manager から注入する環境変数名を指定
      args:
          - build
          - '-t'
          - 'gcr.io/$PROJECT_ID/app'
          - '.'
    # ビルドしたイメージの push
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - push
          - 'gcr.io/$PROJECT_ID/app'
    # 3. Cloud Run へのデプロイ
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      secretEnv: ['GITHUB_WEBHOOK_SECRET']
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              gcloud run deploy app \
                --image gcr.io/$PROJECT_ID/app \
                --region $LOCATION \
                --platform managed \
                --allow-unauthenticated \
                --timeout 600
images:
    - 'gcr.io/$PROJECT_ID/app'

availableSecrets:
    secretManager:
        - versionName: 'projects/$PROJECT_NUMBER/secrets/GITHUB_WEBHOOK_SECRET/versions/1'
          env: 'GITHUB_WEBHOOK_SECRET'

options:
    logging: CLOUD_LOGGING_ONLY
