name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build Docker Image
              run: |
                  docker build -t gcr.io/$GCP_PROJECT_ID/raimei:latest .

            - name: Push Docker Image
              run: |
                  echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
                  docker push gcr.io/$GCP_PROJECT_ID/raimei:latest

            - name: Deploy to Cloud Run
              uses: google-github-actions/deploy-cloudrun@v0
              with:
                  service: raimei-service
                  image: gcr.io/$GCP_PROJECT_ID/raimei:latest
                  region: asia-northeast1
